### ISSUE TITLE
Import without compiling

### ISSUE THREAD

**Issue by EverNife** [alexvasilkov/GradleVcsDependencyPlugin#14]
Is there a way for me to import a git without compiling it?

For example, i have a project that depends on several other projects.
This project an API over it that does not need of all its libs.

I want to add this project as dependency with its code but do not want to try to compile it.

(Maybe this is impossible :/ )

**Comment by alexvasilkov** [comment]
Not sure I understand your question. It does not make sense to import the code but not compile it, your entire project won't compile then because of unresolved dependencies.

Alternatively you can import a single directory of your git repo using `projectPath` param. If you don't really need to add a git repo as project dependency but still want to download it then you can reference it in `settings.gradle` using `fetch` keyword (see readme).

**Comment by EverNife** [comment]
It was a bad interpretation of mine of how these things worked.

Sorry for the nonsense question.

I will have to create a separated module inside my project as an separated API for things to work as i need. Then i will use your projectPath param, ty.
