### ISSUE TITLE
Not working with a private repo

### ISSUE THREAD

**Issue by asllop** [alexvasilkov/GradleVcsDependencyPlugin#15]
I'm using GradleGitDependenciesPlugin v2.0.2

I tried setting directly the user and password like this:

git {
    implementation 'https://github.com/xxx/yyy.git', {
        name 'ModuleName'
        branch 'my_branch'
        projectPath 'ModuleDir'
        user 'usr'
        password 'pass'
    }
}

And using authGroup like this:

git {
    implementation 'https://github.com/xxx/yyy.git', {
        name 'ModuleName'
        branch 'my_branch'
        projectPath 'ModuleDir'
        authGroup 'zzz'
    }
}

And then defining the keys in local.properties:

git.zzz.username=usr
git.zzz.password=pass

But nothing worked, I always get this error:

Cause: https://github.com/xxx/yyy.git: not authorized

Stating the obvious: I do have access to that repo with my credentials, the same credentials I'm using in the GradleGitDependenciesPlugin config.

**Comment by alexvasilkov** [comment]
Hi, was you able to solve the problem? In first case it seems like you should use `username` instead of just `name`. But in this case you should get an error different from "not authorized".

I double checked that both options are working fine for me. I only get "not authorized" error if credentials are invalid, otherwise the sync finishes successfully. So I would assume that you provide invalid credentials after all. Or maybe there are some special characters in your password that breaks the sync, but that is highly unlikely.

**Comment by alexvasilkov** [comment]
Closing for now, feel free to reopen if you still have the issue.
