### ISSUE TITLE
Support import to multiple location 

### ISSUE THREAD

**Issue by Harelfar** [alexvasilkov/GradleVcsDependencyPlugin#21]
Is there a way to import the same repo to 2 different location? 
i.e. to main/resources and also to test/resources
I tried writing 2 dir locations like this:
`dir ./test/resources`
`dir ./main/resources`
 but it just took the last one.

I also tried to duplicate the whole git {} closure, but it took the first one.

**Comment by alexvasilkov** [comment]
You should set different names to you dependencies, in this case you can clone same repo several times.

But I'm not really sure why would you need to import same repo more than once, I would better try to fix the build script so that both `./test/resources` and `./main/resources` are linked to the same directory.
